--Create Database project_1;

CREATE TABLE ERS_USER_ROLES(
	ERS_USER_ROLE_ID INT PRIMARY KEY,
	USER_ROLE VARCHAR(10) NOT NULL
);

CREATE TABLE ERS_REIMBURSEMENT_TYPE(
	REIMB_TYPE_ID INT PRIMARY KEY,
	REIMB_TYPE VARCHAR(10) NOT NULL
);

CREATE TABLE ERS_REIMBURSEMENT_STATUS(
	REIMB_STATUS_ID INT PRIMARY KEY,
	REIMB_STATUS VARCHAR(10) NOT NULL
);

CREATE TABLE ERS_USERS(
	ERS_USERS_ID INT PRIMARY KEY,
	ERS_USERNAME VARCHAR(50) UNIQUE NOT NULL,
	ERS_PASSWORD VARCHAR(50) NOT NULL,
	USER_FIRST_NAME VARCHAR(100) NOT NULL,
	USER_LAST_NAME VARCHAR(100) NOT NULL,
	USER_EMAIL VARCHAR(150) UNIQUE NOT NULL,
	USER_ROLE_ID INT REFERENCES ERS_USER_ROLES (ERS_USER_ROLE_ID)
);

CREATE TABLE ERS_REIMBURSEMENT(
	REIMB_ID INT PRIMARY KEY,
	REIMB_AMOUNT INT NOT NULL,
	REIMB_SUBMITTED TIMESTAMP NOT NULL,
	REIMB_RESOLVED TIMESTAMP,
	REIMB_DESCRIPTION VARCHAR(250),
	REIMB_RECEIPT BYTEA,
	REIMB_AUTHOR INT REFERENCES ERS_USERS(ERS_USERS_ID),
	REIMB_RESOLVER INT REFERENCES ERS_USERS(ERS_USERS_ID),
	REIMB_STATUS_ID INT REFERENCES ERS_REIMBURSEMENT_STATUS(REIMB_STATUS_ID),
	REIMB_TYPE_ID INT REFERENCES ERS_REIMBURSEMENT_TYPE(REIMB_TYPE_ID)
);